services:
  _defaults:
    autowire: true
    autoconfigure: true

  # auto-register all controllers as services
  DivanteLtd\AdvancedSearchBundle\Controller\:
    resource: '../../Controller'
    public: true
    tags: [ 'controller.service_arguments' ]

  bundle.advanced_search.service:
    alias: DivanteLtd\AdvancedSearchBundle\Service\FilterService

  DivanteLtd\AdvancedSearchBundle\Service\FilterService:
    arguments:
      - '@logger'
      - '@pimcore_admin.security.token_storage_user_resolver'
      - '@bundle.advanced_search.filter_locator'
    tags:
      - { name: monolog.logger, channel: pimcore_advanced_search }

  bundle.advanced_search.filter_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ 'container.service_locator' ]

  bundle.advanced_search.filter.default:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\DefaultAdapter
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.calculatedValue:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\CalculatedValue
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.checkbox:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Checkbox
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.country:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Country
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.countrymultiselect:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Countrymultiselect
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.date:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Date
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.datetime:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Datetime
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.input:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Input
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.language:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Language
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.languagemultiselect:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Languagemultiselect
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.localizedfields:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Localizedfields
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.multiselect:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Multiselect
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.numeric:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Numeric
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.quantityValue:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\QuantityValue
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.select:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Select
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.time:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\Time
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.user:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\User
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.many_to_one_relation:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\ManyToOneRelation
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.boolean_select:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\BooleanSelect
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.dynamic_dropdown:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\DynamicDropdown
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.many_to_many_object_relation:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\ManyToManyObjectRelation
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  bundle.advanced_search.filter.advanced_many_to_many_object_relation:
    class: DivanteLtd\AdvancedSearchBundle\Filter\FieldDefinitionAdapter\AdvancedManyToManyObjectRelation
    arguments:
      - '@bundle.advanced_search.service'
      - Symfony\Component\Translation\TranslatorInterface
    shared: false

  DivanteLtd\AdvancedSearchBundle\Installer:
    public: true
    arguments:
      $bundle: "@=service('kernel').getBundle('AdvancedSearchBundle')"
